name: Publish to Docker

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Image
      run: docker build . --tag my-image-name:$(date +%s)
    
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@main
      with:
        name: Jurreh/Password-generator
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}